In [3]:
print('name: muhammad uzair ahmed  \nID : 2841-2017');

name: muhammad uzair ahmed  
ID : 2841-2017


In [5]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np
from sklearn.cluster import KMeans

In [6]:
uzi = pd.read_csv("/home/uzi/Downloads/Salary_Data.csv")

In [7]:
uzi.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [8]:
uzi.tail()

YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [21]:
x = uzi.iloc[:,[0,1]].values
x

array([[1.10000e+00, 3.93430e+04],
       [1.30000e+00, 4.62050e+04],
       [1.50000e+00, 3.77310e+04],
       [2.00000e+00, 4.35250e+04],
       [2.20000e+00, 3.98910e+04],
       [2.90000e+00, 5.66420e+04],
       [3.00000e+00, 6.01500e+04],
       [3.20000e+00, 5.44450e+04],
       [3.20000e+00, 6.44450e+04],
       [3.70000e+00, 5.71890e+04],
       [3.90000e+00, 6.32180e+04],
       [4.00000e+00, 5.57940e+04],
       [4.00000e+00, 5.69570e+04],
       [4.10000e+00, 5.70810e+04],
       [4.50000e+00, 6.11110e+04],
       [4.90000e+00, 6.79380e+04],
       [5.10000e+00, 6.60290e+04],
       [5.30000e+00, 8.30880e+04],
       [5.90000e+00, 8.13630e+04],
       [6.00000e+00, 9.39400e+04],
       [6.80000e+00, 9.17380e+04],
       [7.10000e+00, 9.82730e+04],
       [7.90000e+00, 1.01302e+05],
       [8.20000e+00, 1.13812e+05],
       [8.70000e+00, 1.09431e+05],
       [9.00000e+00, 1.05582e+05],
       [9.50000e+00, 1.16969e+05],
       [9.60000e+00, 1.12635e+05],
       [1.03000e+01,

In [22]:
y = uzi.iloc[:,[0]].values
y

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x, y, test_size=0.20 , random_state=0)

In [38]:
from sklearn.preprocessing import StandardScaler
st_x= StandardScaler()
x_train = st_x.fit_transform(x_train)
x_test = st_x.transform(x_train)
x_train

array([[ 1.75832984,  1.56283548],
       [-0.40973925, -0.72970392],
       [ 0.09356251,  0.37113122],
       [ 1.10016601,  1.1057473 ],
       [-0.83560996, -0.69550196],
       [ 0.01613147, -0.31690082],
       [-0.7194634 , -0.3807875 ],
       [-0.21616165, -0.51525604],
       [ 1.21631257,  1.61030683],
       [ 0.6742953 ,  0.72000731],
       [-1.45505827, -1.11645222],
       [ 2.10676952,  1.93538674],
       [-0.79689444, -0.55401557],
       [-1.1066186 , -1.3711116 ],
       [ 0.32585562,  0.30155767],
       [ 0.36457114,  0.80881947],
       [-0.52588581, -0.67344009],
       [-0.7194634 , -0.78411245],
       [ 1.52603672,  1.27837039],
       [-1.18404964, -1.22454331],
       [-1.53248931, -1.39321381],
       [ 0.79044186,  0.98358017],
       [-0.06129957, -0.23990609],
       [-0.40973925, -0.68279723]])

In [25]:
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [40]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5 ,matric= 'minkoshi', p=2)
classifier.fit(x_train,y_train)

TypeError: __init__() got an unexpected keyword argument 'matric'

In [36]:
y_pred=classifier.predict(x_test)
y_pred

AttributeError: 'KNeighborsClassifier' object has no attribute 'effective_metric_'